# Generated by Django 5.2.8 on 2025-11-19 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lesson_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('lesson_duration', models.PositiveIntegerField(default=10)),
                ('number_of_students', models.PositiveIntegerField(default=12)),
                ('type_of_education', models.CharField(max_length=36)),
                ('level', models.CharField(max_length=48)),
                ('language', models.CharField(max_length=36)),
                ('banner', models.ImageField(upload_to='course_banners/')),
                ('price', models.PositiveIntegerField()),
                ('logo', models.ImageField(upload_to='course_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partners/')),
                ('title', models.CharField(max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=96)),
                ('specialty', models.CharField(max_length=96)),
                ('photo', models.ImageField(upload_to='teacher_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDescriptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_groups', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main.coursedescriptiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='CourseIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='course_icons/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='main.course')),
            ],
        ),
    ]
