# Generated by Django 5.2.8 on 2025-11-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Uzbek', "O'zbek tili"), ('Russian', 'Rus tili'), ('English', 'Ingliz tili')], default='Uzbek', max_length=36),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_time',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_of_education',
            field=models.CharField(default='Offline', max_length=36),
        ),
    ]
